import { Router } from 'express';
import CreateProfessionalSpecialtyServiceLocationController from 'useCases/createProfessionalSpecialtyServiceLocation/CreateProfessionalSpecialtyServiceLocationController';
import FindProfessionalsSpecialtiesServiceLocationsByCpfAndSpecialtyController from 'useCases/findProfessionalsSpecialtiesServiceLocationsByCpfAndSpecialty/FindProfessionalsSpecialtiesServiceLocationsByCpfAndSpecialtyController';
import FindProfessionalsSpecialtiesServiceLocationsByProfessionalController from 'useCases/findProfessionalsSpecialtiesServiceLocationsByProfessional/FindProfessionalsSpecialtiesServiceLocationsByProfessionalController';

const professionalsSpecialtiesServiceLocationsRoutes = Router();

const createProfessionalSpecialtyServiceLocation =
  new CreateProfessionalSpecialtyServiceLocationController();

const findProfessionalsSpecialtiesServiceLocationsByCpfAndSpecialtyController =
  new FindProfessionalsSpecialtiesServiceLocationsByCpfAndSpecialtyController();

const findProfessionalsSpecialtiesServiceLocationsByProfessionalController =
  new FindProfessionalsSpecialtiesServiceLocationsByProfessionalController();

professionalsSpecialtiesServiceLocationsRoutes.post(
  '/',
  createProfessionalSpecialtyServiceLocation.handle,
);

professionalsSpecialtiesServiceLocationsRoutes.get(
  '/findByCpfAndSpecialty/:personCpf/:specialtyId',
  findProfessionalsSpecialtiesServiceLocationsByCpfAndSpecialtyController.handle,
);

professionalsSpecialtiesServiceLocationsRoutes.get(
  '/:professionalId',
  findProfessionalsSpecialtiesServiceLocationsByProfessionalController.handle,
);

export default professionalsSpecialtiesServiceLocationsRoutes;
